---
title: "9/19 Class Work"
author: Briana Allman
format: html
editor: visual
---

This document is what we did in class on 9/192024.

Reading in Packages.

```{r}
library(tidyverse)
library(lubridate)
library(knitr)
library(kableExtra)
```

Reading in .csv file and assigning it to the variable "rice".

```{r}

url <- "https://docs.google.com/spreadsheets/d/1Mk1YGH9LqjF7drJE-td1G_JkdADOU0eMlrP01WFBT8s/pub?gid=0&single=true&output=csv"

rice <- read_csv(url)

names(rice)
```

Standardizing Temperature

```{r}
rice %>% 
  mutate(H2O_Temp = 1.8 * H2O_TempC + 32) %>%
  select(-H2O_TempC) %>%                        
  select(DateTime, H2O_Temp, AirTempF, Rain_in) %>%
  mutate(Date = mdy_hms(DateTime, tz = "EST")) %>% 
  mutate(Weekday = wday(Date, 
                        label = T,
                        abbr = T)) %>% 
  group_by(Weekday) %>% 
  summarise("Average Temp" = mean(H2O_Temp, na.rm = T),
            "Air Temp" = mean(AirTempF),
            "Rain (in)" = mean (Rain_in)) %>% 
  kable() %>% 
  kable_paper()

```
