<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Briana Allman">
<meta name="dcterms.date" content="2024-12-07">

<title>Final Exam (ENVS 543): Impact of Climate-Driven Habitat Suitability on Sex Ratio Divergence in the Sonora Desert Bark Beetle (Araptus attenuatus)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Final_files/libs/clipboard/clipboard.min.js"></script>
<script src="Final_files/libs/quarto-html/quarto.js"></script>
<script src="Final_files/libs/quarto-html/popper.min.js"></script>
<script src="Final_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Final_files/libs/quarto-html/anchor.min.js"></script>
<link href="Final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Final_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Final_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Final_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Final_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="Final_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="Final_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Final Exam (ENVS 543): Impact of Climate-Driven Habitat Suitability on Sex Ratio Divergence in the Sonora Desert Bark Beetle (Araptus attenuatus)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Briana Allman </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 7, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The sex ratio of <em>Araptus attenuatus</em>, a bark beetle species inhabiting <em>Euphorbia lomelli</em> plants in the Sonora Desert, may vary across different populations, potentially influenced by local environmental factors. Understanding the extent to which changing climate may have impacted sex ratio divergence among populations is critical for exploring the species’ evolutionary and ecological dynamics. This study aims to determine if sampled populations of the beetle exhibit different sex ratios and to identify which sites show significant deviations from the expected 1:1 male-to-female ratio. By aggregating the data at the site level and considering plant replication within each site, we can examine if local habitat suitability, as indicated by niche modeling, is related to these observed differences in sex ratio.</p>
<p>Additionally, we will assess if the inclusion of morphological traits, such as Phenotype A and Phenotype B, improves the functional relationship between habitat suitability and sex ratio. By comparing current habitat suitability with projections from the last glacial maximum, we will investigate whether habitat conditions have changed over time and how these changes may have influenced sex ratio distribution. Lastly, we will apply the current model to predict the historical sex ratio, examining how climate variations, as measured by habitat suitability, may have shaped sex ratio patterns across the landscape.</p>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods:</h2>
<section id="data-overview" class="level4">
<h4 class="anchored" data-anchor-id="data-overview"><strong>Data Overview</strong></h4>
<p>This study uses four datasets to examine the relationship between habitat suitability and sex ratio divergence in the Sonora Desert bark beetle (<em>Araptus attenuatus</em>), with a focus on current and historical climate conditions.</p>
<section id="arapat_locations.csv" class="level5">
<h5 class="anchored" data-anchor-id="arapat_locations.csv"><strong>1. Arapat_Locations.csv</strong></h5>
<p>This dataset contains the spatial coordinates (latitude and longitude) for 31 sampling sites within the Sonora Desert. These locations serve as the basis for analyzing beetle distribution and sex ratio variations across different habitat conditions, which are influenced by the local environment.</p>
</section>
<section id="arapat_samples.csv" class="level5">
<h5 class="anchored" data-anchor-id="arapat_samples.csv"><strong>2. Arapat_Samples.csv</strong></h5>
<p>The Arapat_Samples.csv dataset includes 3100 beetle observations across the 31 sites, detailing sex, phenotypic traits (Phenotype A and Phenotype B), and plant associations. It supports the analysis of sex ratio differences and their potential correlation with habitat suitability and phenotypic traits.</p>
</section>
<section id="suitability_now.tif" class="level5">
<h5 class="anchored" data-anchor-id="suitability_now.tif"><strong>3. Suitability_now.tif</strong></h5>
<p>This raster dataset represents the current habitat suitability for <em>Araptus attenuatus</em>, derived from niche modeling based on biological and climatic factors. It provides a measure of habitat conditions across the sampling sites, enabling us to investigate the relationship between current habitat suitability and beetle sex ratio.</p>
</section>
<section id="suitability_lgm.asc" class="level5">
<h5 class="anchored" data-anchor-id="suitability_lgm.asc"><strong>4. Suitability_lgm.asc</strong></h5>
<p>This raster dataset estimates habitat suitability during the Last Glacial Maximum (~20,000 years ago), using climate reconstruction methods. It allows for comparison with the current suitability data to explore how past climate conditions may have influenced beetle distribution and sex ratio patterns.</p>
</section>
</section>
<section id="dataset-integration" class="level4">
<h4 class="anchored" data-anchor-id="dataset-integration"><strong>Dataset Integration</strong></h4>
<p>Together, these datasets allow for a comprehensive analysis of how changing habitat suitability, both currently and historically, influences the sex ratio of <em>Araptus attenuatus</em>. The combination of spatial, population, and environmental data helps to reveal trends in sex ratio divergence linked to ecological and climatic factors.</p>
<hr>
<hr>
<p><strong>1. Sex Ratio Analysis Across Populations</strong></p>
<p><em>Question: Do sampled populations of the beetle have different sex ratios? You can consider the plant to be replicated within each site.</em></p>
<p><br>
To determine if the sex ratios differ among sampled populations, the proportion of males and females for each site will be calculated.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Table 1: Sex Ratios Across Sampling Sites</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Site</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Males</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Females</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Total</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Male Ratio</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Female Ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 1</td>
<td style="text-align: center;">46</td>
<td style="text-align: center;">54</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.46</td>
<td style="text-align: center; color: red !important;">0.54</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 10</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.60</td>
<td style="text-align: center; color: red !important;">0.40</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 11</td>
<td style="text-align: center;">56</td>
<td style="text-align: center;">44</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.56</td>
<td style="text-align: center; color: red !important;">0.44</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 12</td>
<td style="text-align: center;">54</td>
<td style="text-align: center;">46</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.54</td>
<td style="text-align: center; color: red !important;">0.46</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 13</td>
<td style="text-align: center;">57</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.57</td>
<td style="text-align: center; color: red !important;">0.43</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 14</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.40</td>
<td style="text-align: center; color: red !important;">0.60</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 15</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.45</td>
<td style="text-align: center; color: red !important;">0.55</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 16</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">47</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.53</td>
<td style="text-align: center; color: red !important;">0.47</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 17</td>
<td style="text-align: center;">62</td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.62</td>
<td style="text-align: center; color: red !important;">0.38</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 18</td>
<td style="text-align: center;">69</td>
<td style="text-align: center;">31</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.69</td>
<td style="text-align: center; color: red !important;">0.31</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 19</td>
<td style="text-align: center;">47</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.47</td>
<td style="text-align: center; color: red !important;">0.53</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 2</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">41</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.59</td>
<td style="text-align: center; color: red !important;">0.41</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 20</td>
<td style="text-align: center;">62</td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.62</td>
<td style="text-align: center; color: red !important;">0.38</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 21</td>
<td style="text-align: center;">63</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.63</td>
<td style="text-align: center; color: red !important;">0.37</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 22</td>
<td style="text-align: center;">57</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.57</td>
<td style="text-align: center; color: red !important;">0.43</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 23</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.50</td>
<td style="text-align: center; color: red !important;">0.50</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 24</td>
<td style="text-align: center;">54</td>
<td style="text-align: center;">46</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.54</td>
<td style="text-align: center; color: red !important;">0.46</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 25</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.50</td>
<td style="text-align: center; color: red !important;">0.50</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 26</td>
<td style="text-align: center;">49</td>
<td style="text-align: center;">51</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.49</td>
<td style="text-align: center; color: red !important;">0.51</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 27</td>
<td style="text-align: center;">46</td>
<td style="text-align: center;">54</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.46</td>
<td style="text-align: center; color: red !important;">0.54</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 28</td>
<td style="text-align: center;">52</td>
<td style="text-align: center;">48</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.52</td>
<td style="text-align: center; color: red !important;">0.48</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 29</td>
<td style="text-align: center;">62</td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.62</td>
<td style="text-align: center; color: red !important;">0.38</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 3</td>
<td style="text-align: center;">58</td>
<td style="text-align: center;">42</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.58</td>
<td style="text-align: center; color: red !important;">0.42</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 30</td>
<td style="text-align: center;">49</td>
<td style="text-align: center;">51</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.49</td>
<td style="text-align: center; color: red !important;">0.51</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 31</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">57</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.43</td>
<td style="text-align: center; color: red !important;">0.57</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 4</td>
<td style="text-align: center;">46</td>
<td style="text-align: center;">54</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.46</td>
<td style="text-align: center; color: red !important;">0.54</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 5</td>
<td style="text-align: center;">49</td>
<td style="text-align: center;">51</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.49</td>
<td style="text-align: center; color: red !important;">0.51</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 6</td>
<td style="text-align: center;">42</td>
<td style="text-align: center;">58</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.42</td>
<td style="text-align: center; color: red !important;">0.58</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 7</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.55</td>
<td style="text-align: center; color: red !important;">0.45</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 8</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">47</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.53</td>
<td style="text-align: center; color: red !important;">0.47</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 9</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">63</td>
<td style="text-align: center;">100</td>
<td style="text-align: center; color: blue !important;">0.37</td>
<td style="text-align: center; color: red !important;">0.63</td>
</tr>
</tbody>
</table>


</div>
</div>
<hr>
<p><strong>2. Identifying Sites with Deviations from Equal Sex Ratios</strong></p>
<p><em>Question: Which sites have sex ratios that deviate from equal proportions of males and females at the site?</em></p>
<p><br>
For each site, statistical tests (e.g., chi-square goodness-of-fit tests) will identify sites where the sex ratio significantly deviates from equal proportions. Results will be summarized in a table.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Table 2: Sites with Significant Deviations in Sex Ratio (p &lt; 0.05)</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Site</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Males</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Females</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Total</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Male Ratio</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Female Ratio</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Longitude</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Latitude</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 10</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">0.60</td>
<td style="text-align: center;">0.40</td>
<td style="text-align: center; color: red !important;">0.046</td>
<td style="text-align: center;">26.638</td>
<td style="text-align: center;">-109.327</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 14</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">0.40</td>
<td style="text-align: center;">0.60</td>
<td style="text-align: center; color: red !important;">0.046</td>
<td style="text-align: center;">24.214</td>
<td style="text-align: center;">-110.273</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 17</td>
<td style="text-align: center;">62</td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">0.62</td>
<td style="text-align: center;">0.38</td>
<td style="text-align: center; color: red !important;">0.016</td>
<td style="text-align: center;">25.025</td>
<td style="text-align: center;">-111.675</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 18</td>
<td style="text-align: center;">69</td>
<td style="text-align: center;">31</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">0.69</td>
<td style="text-align: center;">0.31</td>
<td style="text-align: center; color: red !important;">0.000</td>
<td style="text-align: center;">24.008</td>
<td style="text-align: center;">-109.851</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 20</td>
<td style="text-align: center;">62</td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">0.62</td>
<td style="text-align: center;">0.38</td>
<td style="text-align: center; color: red !important;">0.016</td>
<td style="text-align: center;">28.728</td>
<td style="text-align: center;">-113.490</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 21</td>
<td style="text-align: center;">63</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">0.63</td>
<td style="text-align: center;">0.37</td>
<td style="text-align: center; color: red !important;">0.009</td>
<td style="text-align: center;">26.209</td>
<td style="text-align: center;">-111.378</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold;">Site 29</td>
<td style="text-align: center;">62</td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">0.62</td>
<td style="text-align: center;">0.38</td>
<td style="text-align: center; color: red !important;">0.016</td>
<td style="text-align: center;">27.363</td>
<td style="text-align: center;">-112.964</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Site 9</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">63</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">0.37</td>
<td style="text-align: center;">0.63</td>
<td style="text-align: center; color: red !important;">0.009</td>
<td style="text-align: center;">28.408</td>
<td style="text-align: center;">-112.870</td>
</tr>
</tbody>
</table>


</div>
</div>
<hr>
<p><strong>3. Functional Relationship Between Habitat Suitability and Sex Ratio</strong></p>
<p><em>Question: Is there a functional relationship between the habitat suitability at the sampling locations and the sex ratio? Since all of our suitability measurements are taken from raster data with a cell size of 1.0 km<sup><sub>2</sub></sup> (e.g., all plants are in the same grid cell), collapse the sex ratio estimates to a single value per site.</em></p>
<p><br>
The habitat suitability index from raster data will be linked to the sampling locations using spatial joins. Sex ratios will be collapsed to a single value per site, and a regression model will evaluate the relationship between habitat suitability and sex ratios.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/chunk4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Table 3: Male Sex Ratio Regression Summary</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.5494204</td>
<td style="text-align: right;">0.0307049</td>
<td style="text-align: right;">17.8935858</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">suitability_now</td>
<td style="text-align: right;">-0.0583158</td>
<td style="text-align: right;">0.0634776</td>
<td style="text-align: right;">-0.9186818</td>
<td style="text-align: right;">0.3661086</td>
</tr>
</tbody>
</table>


</div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Table 4: Female Sex Ratio Regression Summary</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.4505796</td>
<td style="text-align: right;">0.0307049</td>
<td style="text-align: right;">14.6745264</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">suitability_now</td>
<td style="text-align: right;">0.0583158</td>
<td style="text-align: right;">0.0634776</td>
<td style="text-align: right;">0.9186818</td>
<td style="text-align: right;">0.3661086</td>
</tr>
</tbody>
</table>


</div>
</div>
<hr>
<p><strong>4. Effect of Phenotypic Traits on Functional Relationship</strong></p>
<p><em>Question: Does the inclusion of <code style="font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 0.75rem; border-radius: 6px; background-color: rgb(245, 245, 245); border: 1px solid rgb(199, 205, 209); padding: 0.125rem 0.25rem; color: rgb(224, 6, 31); text-size-adjust: auto;">Phenotype A</code> and <code style="font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 0.75rem; border-radius: 6px; background-color: rgb(245, 245, 245); border: 1px solid rgb(199, 205, 209); padding: 0.125rem 0.25rem; color: rgb(224, 6, 31); text-size-adjust: auto;">Phenotype B</code> improve the functional relationship over habitat suitability alone?</em></p>
<p><br>
Phenotype A and Phenotype B will be incorporated as additional predictors in a multivariate regression model to determine if they improve the explanatory power of the habitat-suitability model.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Model 1: Male Sex Ratio - Habitat Suitability Only</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.5494204</td>
<td style="text-align: right;">0.0029674</td>
<td style="text-align: right;">185.15446</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">suitability_now</td>
<td style="text-align: right;">-0.0583158</td>
<td style="text-align: right;">0.0061346</td>
<td style="text-align: right;">-9.50609</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>


</div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Model 2: Male Sex Ratio - Habitat Suitability + Phenotypes</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.5542841</td>
<td style="text-align: right;">0.0048678</td>
<td style="text-align: right;">113.866801</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">suitability_now</td>
<td style="text-align: right;">-0.0523140</td>
<td style="text-align: right;">0.0062856</td>
<td style="text-align: right;">-8.322816</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PhenotypeA</td>
<td style="text-align: right;">0.0047854</td>
<td style="text-align: right;">0.0014021</td>
<td style="text-align: right;">3.412910</td>
<td style="text-align: right;">0.0006513</td>
</tr>
<tr class="even">
<td style="text-align: left;">PhenotypeB</td>
<td style="text-align: right;">-0.0074128</td>
<td style="text-align: right;">0.0012846</td>
<td style="text-align: right;">-5.770599</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>


</div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Model 3: Female Sex Ratio - Habitat Suitability Only</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.4505796</td>
<td style="text-align: right;">0.0029674</td>
<td style="text-align: right;">151.84514</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">suitability_now</td>
<td style="text-align: right;">0.0583158</td>
<td style="text-align: right;">0.0061346</td>
<td style="text-align: right;">9.50609</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>


</div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Model 4: Female Sex Ratio - Habitat Suitability + Phenotypes</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.4457159</td>
<td style="text-align: right;">0.0048678</td>
<td style="text-align: right;">91.563598</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">suitability_now</td>
<td style="text-align: right;">0.0523140</td>
<td style="text-align: right;">0.0062856</td>
<td style="text-align: right;">8.322816</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PhenotypeA</td>
<td style="text-align: right;">-0.0047854</td>
<td style="text-align: right;">0.0014021</td>
<td style="text-align: right;">-3.412910</td>
<td style="text-align: right;">0.0006513</td>
</tr>
<tr class="even">
<td style="text-align: left;">PhenotypeB</td>
<td style="text-align: right;">0.0074128</td>
<td style="text-align: right;">0.0012846</td>
<td style="text-align: right;">5.770599</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>


</div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>ANOVA Comparison 1: Male Sex Ratio Models</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df.residual</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">rss</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sumsq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Male_Ratio ~ suitability_now</td>
<td style="text-align: right;">2998</td>
<td style="text-align: right;">16.55468</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Male_Ratio ~ suitability_now + PhenotypeA + PhenotypeB</td>
<td style="text-align: right;">2996</td>
<td style="text-align: right;">16.29764</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.2570383</td>
<td style="text-align: right;">23.62572</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>


</div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>ANOVA Comparison 2: Female Sex Ratio Models</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df.residual</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">rss</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sumsq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Female_Ratio ~ suitability_now</td>
<td style="text-align: right;">2998</td>
<td style="text-align: right;">16.55468</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Female_Ratio ~ suitability_now + PhenotypeA + PhenotypeB</td>
<td style="text-align: right;">2996</td>
<td style="text-align: right;">16.29764</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.2570383</td>
<td style="text-align: right;">23.62572</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>


</div>
</div>
<hr>
<p><strong>5. Change in Habitat Suitability from LGM to Present</strong></p>
<p><em>Question: Using the data from the last glacial maximum and the sampling locations, has the suitability changed at each location (e.g., was it as suitable 20,000 years ago as today)?</em></p>
<p><br>
Raster data representing habitat suitability from the Last Glacial Maximum (LGM) and the present will be extracted for each sampling site. Paired t-tests will assess if suitability has changed significantly over time.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Table 5: Suitability Change Across Sampling Locations</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: white !important;">Site</th>
<th data-quarto-table-cell-role="th" style="text-align: right; background-color: white !important;">Suitability Now</th>
<th data-quarto-table-cell-role="th" style="text-align: right; background-color: white !important;">Suitability LGM</th>
<th data-quarto-table-cell-role="th" style="text-align: right; background-color: white !important;">Suitability Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Site 1</td>
<td style="text-align: right;">0.8810290</td>
<td style="text-align: right;">0.9227720</td>
<td style="text-align: right;">-0.0417430</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Site 2</td>
<td style="text-align: right;">0.1879650</td>
<td style="text-align: right;">0.1890130</td>
<td style="text-align: right;">-0.0010480</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Site 3</td>
<td style="text-align: right;">0.6163620</td>
<td style="text-align: right;">0.6118770</td>
<td style="text-align: right;">0.0044850</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Site 4</td>
<td style="text-align: right;">0.2876230</td>
<td style="text-align: right;">0.2251980</td>
<td style="text-align: right;">0.0624250</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Site 5</td>
<td style="text-align: right;">0.4613570</td>
<td style="text-align: right;">0.3898320</td>
<td style="text-align: right;">0.0715250</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Site 6</td>
<td style="text-align: right;">0.2673030</td>
<td style="text-align: right;">0.5051860</td>
<td style="text-align: right;">-0.2378830</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Site 7</td>
<td style="text-align: right;">0.9018780</td>
<td style="text-align: right;">0.9347510</td>
<td style="text-align: right;">-0.0328730</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Site 8</td>
<td style="text-align: right;">0.4964650</td>
<td style="text-align: right;">0.4916560</td>
<td style="text-align: right;">0.0048090</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Site 9</td>
<td style="text-align: right;">0.5242670</td>
<td style="text-align: right;">0.3556450</td>
<td style="text-align: right;">0.1686220</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Site 10</td>
<td style="text-align: right;">0.0562845</td>
<td style="text-align: right;">0.0541657</td>
<td style="text-align: right;">0.0021188</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Site 11</td>
<td style="text-align: right;">0.2185940</td>
<td style="text-align: right;">0.1673550</td>
<td style="text-align: right;">0.0512390</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Site 12</td>
<td style="text-align: right;">0.1627240</td>
<td style="text-align: right;">0.4716300</td>
<td style="text-align: right;">-0.3089060</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Site 13</td>
<td style="text-align: right;">0.3651910</td>
<td style="text-align: right;">0.3316630</td>
<td style="text-align: right;">0.0335280</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Site 14</td>
<td style="text-align: right;">0.6195190</td>
<td style="text-align: right;">0.6867450</td>
<td style="text-align: right;">-0.0672260</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Site 15</td>
<td style="text-align: right;">0.4125120</td>
<td style="text-align: right;">0.4853990</td>
<td style="text-align: right;">-0.0728870</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Site 16</td>
<td style="text-align: right;">0.3519050</td>
<td style="text-align: right;">0.2463260</td>
<td style="text-align: right;">0.1055790</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Site 17</td>
<td style="text-align: right;">0.1744380</td>
<td style="text-align: right;">0.3211760</td>
<td style="text-align: right;">-0.1467380</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Site 18</td>
<td style="text-align: right;">0.1455230</td>
<td style="text-align: right;">0.4471890</td>
<td style="text-align: right;">-0.3016660</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Site 19</td>
<td style="text-align: right;">0.8625610</td>
<td style="text-align: right;">0.7814810</td>
<td style="text-align: right;">0.0810800</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Site 20</td>
<td style="text-align: right;">0.4214400</td>
<td style="text-align: right;">0.3992860</td>
<td style="text-align: right;">0.0221540</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Site 21</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.7124060</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Site 22</td>
<td style="text-align: right;">0.7217000</td>
<td style="text-align: right;">0.7615080</td>
<td style="text-align: right;">-0.0398080</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Site 23</td>
<td style="text-align: right;">0.4328730</td>
<td style="text-align: right;">0.4039260</td>
<td style="text-align: right;">0.0289470</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Site 24</td>
<td style="text-align: right;">0.4226090</td>
<td style="text-align: right;">0.7239640</td>
<td style="text-align: right;">-0.3013550</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Site 25</td>
<td style="text-align: right;">0.2791050</td>
<td style="text-align: right;">0.3565710</td>
<td style="text-align: right;">-0.0774660</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Site 26</td>
<td style="text-align: right;">0.3975000</td>
<td style="text-align: right;">0.3218530</td>
<td style="text-align: right;">0.0756470</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Site 27</td>
<td style="text-align: right;">0.7324870</td>
<td style="text-align: right;">0.7211120</td>
<td style="text-align: right;">0.0113750</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Site 28</td>
<td style="text-align: right;">0.5264130</td>
<td style="text-align: right;">0.4898480</td>
<td style="text-align: right;">0.0365650</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Site 29</td>
<td style="text-align: right;">0.3210530</td>
<td style="text-align: right;">0.2485630</td>
<td style="text-align: right;">0.0724900</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Site 30</td>
<td style="text-align: right;">0.2617900</td>
<td style="text-align: right;">0.3431230</td>
<td style="text-align: right;">-0.0813330</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Site 31</td>
<td style="text-align: right;">0.3953470</td>
<td style="text-align: right;">0.3444950</td>
<td style="text-align: right;">0.0508520</td>
</tr>
</tbody>
</table>


</div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Table 6: Paired t-test Results: Suitability Change (LGM to Present)</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: lightgray !important;">Statistic</th>
<th data-quarto-table-cell-role="th" style="text-align: right; background-color: lightgray !important;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; color: blue !important;">t</td>
<td style="text-align: right; width: 3in; color: blue !important;">-1.2340</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Degrees of Freedom (df)</td>
<td style="text-align: right; width: 3in;">29.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">p-value</td>
<td style="text-align: right; width: 3in;">0.2271</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">95% CI Lower</td>
<td style="text-align: right; width: 3in;">-0.0733</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">95% CI Upper</td>
<td style="text-align: right; width: 3in;">0.0181</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Mean Difference</td>
<td style="text-align: right; width: 3in;">-0.0276</td>
</tr>
</tbody>
</table>


</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/chunk6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<p><strong>6. Predicting Historical Sex Ratios</strong></p>
<p><em>Question: Predict the distribution of the historical sex ratio by applying the model you developed for current conditions to the suitability estimated from the last glacial maximum. Across the landscape, do you detect any trends that may be due to the differences in climate, as measured by our estimates of habitat suitability?</em></p>
<p><br>
The regression model developed for current conditions will be applied to the LGM suitability data to predict historical sex ratios. These predictions will be visualized spatially to identify trends influenced by historical climate conditions.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/chunk7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Table 7: Sex Ratios Across Sites (Current vs Historical)</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; background-color: rgba(220, 227, 244, 255) !important;">Site</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; background-color: rgba(220, 227, 244, 255) !important;">Time Period</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; background-color: rgba(220, 227, 244, 255) !important;">Sex Ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Site 1</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.4600000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 1</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6133472</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 10</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.6000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 10</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6377662</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 11</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.5600000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 11</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6346515</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 12</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.5400000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 12</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6261466</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 13</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.5700000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 13</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6300793</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 14</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.4000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 14</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6200567</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 15</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.4500000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 15</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6257582</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 16</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.5300000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 16</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6324608</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 17</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.6200000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 17</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6303727</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 18</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.6900000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 18</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6268354</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 19</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.4700000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 19</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6173647</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 2</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.5900000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 2</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6340520</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 20</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.6200000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 20</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6281830</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 21</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6193278</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 22</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.5700000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 22</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6179325</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 23</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.5000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 23</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6280526</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 24</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.5400000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 24</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6189995</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 25</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.5000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 25</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6293817</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 26</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.4900000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 26</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6303537</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 27</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.4600000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 27</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6190805</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 28</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.5200000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 28</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6256326</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 29</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.6200000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 29</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6323985</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 3</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.5800000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 3</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6221808</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 30</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.4900000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 30</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6297585</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 31</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.4300000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 31</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6297200</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 4</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.4600000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 4</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6330482</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 5</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.4900000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 5</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6284485</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 6</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.4200000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 6</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6251996</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 7</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.5500000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 7</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6130067</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 8</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.5300000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 8</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6255816</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site 9</td>
<td style="text-align: left;">Current</td>
<td style="text-align: right; color: red !important;">0.3700000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Site 9</td>
<td style="text-align: left;">Historical</td>
<td style="text-align: right; color: red !important;">0.6294076</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `size` argument of `element_line()` is deprecated as of ggplot2 3.4.0.
ℹ Please use the `linewidth` argument instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/chunk8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/chunk8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results:</h2>
<p><strong>Do sampled populations of the beetle have different sex ratios? You can consider the plant to be replicated within each site.</strong></p>
<p>The results of this analysis indicate that the sampled populations of the beetle exhibit different sex ratios across the various sites. For each site, the number of male and female beetles was recorded, and the sex ratio was calculated as the proportion of males to total individuals. The sex ratios varied significantly between sites, with male proportions ranging from 0.40 to 0.69 (40% to 69% male), and female proportions ranging from 0.31 to 0.60 (31% to 60% female).</p>
<p>As shown in <code>Table 1: Sex Ratios Across Sampling Sites</code>, Site 1 had a male proportion of 0.46 and a female proportion of 0.54. In contrast, Site 10 exhibited a higher male proportion of 0.60, with the female proportion being 0.40. Other sites, such as Site 11 and Site 12, displayed more balanced ratios, with male proportions of 0.56 and 0.54, respectively. Notably, Site 14 had the lowest male proportion of 0.40, with females comprising 60% of the population. Conversely, Site 18 demonstrated the highest male proportion of 0.69, with females accounting for only 31% of the population.</p>
<p>These findings, summarized in Table 1, suggest that there is notable variation in the sex ratios of beetle populations across the sampled sites. Given that the plant is considered to be replicated within each site, the variation in sex ratios may be influenced by factors at the site level, such as environmental conditions or other ecological variables. The observed differences in sex ratios across sites indicate that the populations are not uniform, and further investigation is required to explore the potential causes behind these variations.</p>
<hr>
<p><strong>Which sites have sex ratios that deviate from equal proportions of males and females at the site?</strong></p>
<p>This analysis aimed to determine whether the sampled populations of the beetle exhibited different sex ratios across various sites. The results indicate that several sites demonstrated significant deviations from the expected 50:50 male-to-female ratio. As shown in <code>Table 2: Sites with Significant Deviations in Sex Ratio (p &lt; 0.05)</code>, Sites 10, 14, 17, 18, 20, 21, 29, and 9 exhibited p-values less than 0.05, indicating that the observed sex ratios at these sites were significantly different from equal proportions.</p>
<p>For example, Site 18 had a notably higher male ratio of 0.69, while Site 9 exhibited a higher female ratio of 0.63. These deviations suggest that, at these sites, factors influencing sex determination or survival may be skewing the sex ratio. Some sites, such as Site 10 and Site 14, showed more moderate imbalances, with a male ratio of 0.60 at Site 10 and 0.40 at Site 14. However, the statistical evidence supports the conclusion that sex ratios at these sites are not random.</p>
<p>The findings provide compelling evidence that populations across the surveyed sites do not exhibit equal sex ratios. The results summarized in Table 2 highlight the need for further investigation into the factors contributing to these differences, as they may provide insights into underlying ecological, environmental, or genetic processes influencing beetle population dynamics. Understanding the causes of such deviations is crucial for interpreting population trends and can inform conservation and management strategies, particularly in light of environmental changes that may further impact sex ratio distributions.</p>
<hr>
<p><strong>Is there a functional relationship between the <em>habitat suitability</em> at the sampling locations and the sex ratio? Since all of our suitability measurements are taken from raster data with a cell size of 1.0 km<sup><sub>2</sub></sup> (e.g., all plants are in the same grid cell), collapse the sex ratio estimates to a single value per site.</strong></p>
<p>This analysis examined whether habitat suitability, measured at a 1.0 km² resolution, influences the sex ratio of beetle populations across 31 sampling sites. To explore this, linear regression models were constructed to investigate the relationship between habitat suitability and male and female sex ratios, respectively.</p>
<p><strong>Male Sex Ratio and Habitat Suitability</strong>: The regression analysis for male sex ratios revealed a weak negative relationship with habitat suitability, though the relationship was not statistically significant (β₁ = −0.058, p = 0.366) (<code>Figure 1: Male Sex Ratio vs. Habitat Suitability</code>). The intercept was highly significant (p &lt; 0.001), with a value of 0.549, indicating that, on average, male beetles made up 54.9% of the population. However, the lack of significance for the slope suggests that habitat suitability does not meaningfully predict variations in the male sex ratio across the sampled sites. The detailed regression results for the male sex ratio are provided in <code>Table 3: Male Sex Ratio Regression Summary</code>.</p>
<p><strong>Female Sex Ratio and Habitat Suitability</strong>: Similarly, the regression analysis for female sex ratios showed a weak positive relationship with habitat suitability, with no significant association (β₁ = 0.058, p = 0.366) (<code>Figure 2: Female Sex Ratio vs. Habitat Suitability</code>). Like the male model, the intercept was highly significant (p &lt; 0.001), with a value of 0.451, suggesting that females made up 45.1% of the population on average. The positive but non-significant slope further indicates that habitat suitability does not significantly influence the female sex ratio. Full regression results for the female sex ratio are presented in <code>Table 4: Female Sex Ratio Regression Summary</code>.</p>
<p><strong>Regression Summaries</strong>: The regression results for both male and female sex ratios are summarized in Table 3 and Table 4, respectively. For the male sex ratio, the estimated coefficient for habitat suitability was −0.058, with a standard error of 0.063, and the p-value was 0.366. For the female sex ratio, the estimated coefficient was 0.058, also with a standard error of 0.063, and the p-value was similarly 0.366. Both models exhibit weak slopes, reinforcing the lack of a significant relationship between habitat suitability and sex ratio at the sampled sites.</p>
<hr>
<p><strong>Does the inclusion of <code style="font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 0.75rem; border-radius: 6px; background-color: rgb(245, 245, 245); border: 1px solid rgb(199, 205, 209); padding: 0.125rem 0.25rem; color: rgb(224, 6, 31); text-size-adjust: auto;">Phenotype A</code> and <code style="font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 0.75rem; border-radius: 6px; background-color: rgb(245, 245, 245); border: 1px solid rgb(199, 205, 209); padding: 0.125rem 0.25rem; color: rgb(224, 6, 31); text-size-adjust: auto;">Phenotype B</code> improve the functional relationship over <em>habitat suitability</em> alone?</strong></p>
<p>In this analysis, the aim was to evaluate the functional relationship between habitat suitability and sex ratios at various sampling locations, with a particular focus on the additional influence of phenotypic traits (Phenotype A and Phenotype B). Linear regression models were employed to examine the effects of habitat suitability and phenotypic traits on the male and female sex ratios.</p>
<p>The analysis revealed that habitat suitability (measured as suitability_now) is a significant predictor of sex ratios for both males and females. Specifically, in <code>Model 1: Male Sex Ratio - Habitat Suitability Only</code>, there was a significant negative relationship between habitat suitability and male sex ratio, as indicated by a p-value &lt; 2e-16. Similarly, in <code>Model 3: Female Sex Ratio - Habitat Suitability Only</code>, habitat suitability was positively correlated with the female sex ratio, also with a highly significant p-value (&lt; 2e-16). These results suggest that the suitability of the environment plays a crucial role in determining sex ratio distributions at the sampling sites.</p>
<p>When phenotypic traits were incorporated into the models, a notable improvement in explanatory power was observed. In <code>Model 2: Male Sex Ratio - Habitat Suitability + Phenotypes</code> and <code>Model 4: Female Sex Ratio - Habitat Suitability + Phenotypes</code>, the inclusion of Phenotype A and Phenotype B significantly improved model fit. Specifically, for males, Phenotype A was positively correlated with the male sex ratio, while Phenotype B showed a negative correlation. For females, the relationships were reversed: Phenotype A was negatively correlated with the female sex ratio, while Phenotype B showed a positive correlation. These findings suggest that phenotypic traits may influence sex ratio outcomes, potentially through mechanisms such as differential survival or reproductive success.</p>
<p>Model comparisons using ANOVA confirmed the significant improvement in the models when phenotypic traits were included. <code>ANOVA Comparison 1: Male Sex Ratio Models</code> and <code>ANOVA Comparison 2: Female Sex Ratio Models</code> both showed highly significant p-values (6.6e-11 for both sexes), indicating that the addition of phenotypic traits contributed meaningfully to the models. The inclusion of these variables increased the R-squared value from 2.93% in the base models (Model 1 and Model 3) to 4.43% in the extended models (Model 2 and Model 4), suggesting that phenotypic traits provided valuable explanatory power. However, the relatively low R-squared values still indicate that other unaccounted factors may also be influencing sex ratios.</p>
<p>These findings underscore the importance of considering both environmental and phenotypic factors when investigating sex ratio patterns in natural populations. While habitat suitability remains a critical driver of sex ratios, the inclusion of phenotypic traits provides further insight into the biological processes that may shape these ratios. This offers a more comprehensive understanding of the factors influencing sex determination in these populations.</p>
<p>Despite these advances, the models’ low R-squared values suggest that additional variables, such as genetic factors, behavioral influences, or local environmental conditions not captured in this study, may also contribute significantly to sex ratio variation. Future research should explore these additional factors and their potential interactions with habitat suitability and phenotypic traits to further elucidate the complex determinants of sex ratios in natural populations.</p>
<hr>
<p><strong>Using the data from the last glacial maximum and the sampling locations, has the <em>suitability</em> changed at each location (e.g., was it as suitable 20,000 years ago as today)?</strong></p>
<p>The analysis of habitat suitability data, comparing conditions during the Last Glacial Maximum (LGM) and the present, was conducted at 31 sampling locations to assess how suitability has changed over time. The results show varying degrees of change, with some sites exhibiting relatively minor fluctuations while others demonstrated more substantial shifts.</p>
<p><code>Figure 3: Boxplot of Suitability Change from LGM to Present</code> presents a boxplot of suitability change across all sites. The median suitability change is approximately zero, indicating that, on the whole, habitat suitability has remained stable across most sites. This suggests that, in general, there has not been a significant shift in suitability between the LGM and present. The interquartile range (IQR), representing the middle 50% of data points, further supports this observation, with most changes falling within a narrow band around zero. This pattern reflects a general stability in suitability across the majority of locations.</p>
<p>However, there is notable variability in the changes observed. While many sites showed only minor changes, a few sites experienced more significant shifts. For instance, Site 6, Site 12, and Site 18 exhibited substantial decreases in suitability, with changes exceeding -0.2, indicating that these sites were more suitable for the studied species during the LGM than they are today. Conversely, Site 9 and Site 16 demonstrated improvements in suitability, suggesting that these areas have become more favorable over time.</p>
<p>An outlier is also evident in the data: Site 12 showed a particularly large negative change in suitability, with a decrease of approximately -0.31. This suggests that environmental factors at this site may have driven a more dramatic decline in habitat suitability. Further investigation into such outliers could provide valuable insights into the specific conditions or disturbances that contributed to these shifts.</p>
<p>To assess whether the observed changes were statistically significant, a paired t-test was performed, comparing suitability values from the LGM and present. The test revealed a mean difference of -0.0276 in suitability, with a p-value of 0.2271, suggesting that the changes are not statistically significant. The 95% confidence interval for the mean difference ranged from -0.073 to 0.018, which further supports the conclusion that the changes in suitability are not different from zero on average. <code>Table 6: Paired t-test Results: Suitability Change (LGM to Present)</code> provides the detailed statistical results of the test.</p>
<p>In conclusion, the data indicate a general trend of stability in habitat suitability across the 31 sampling locations. While some sites showed minor positive or negative changes, the majority of locations exhibited minimal fluctuation. The presence of significant outliers, particularly in the case of Site 12, underscores the importance of considering localized environmental factors that could drive more pronounced shifts in habitat suitability. Although the paired t-test did not find significant overall changes, the variability observed across sites warrants further investigation into the specific ecological processes and environmental factors influencing suitability at individual locations. Such insights are crucial for informing conservation efforts, particularly in the context of ongoing climate change and habitat restoration initiatives. <code>Table 5: Suitability Change Across Sampling Locations</code> summarizes the suitability changes observed across all sites.</p>
<hr>
<p><strong>Predict the distribution of the historical sex ratio by applying the model you developed for current conditions to the <em>suitability</em> estimated from the last glacial maximum. Across the landscape, do you detect any trends that may be due to the differences in climate, as measured by our estimates of <em>habitat suitability?</em></strong></p>
<p>To understand the influence of climatic changes on the sex ratio distribution of <em>Araptus attenuatus</em>, a model developed for current conditions was applied to habitat suitability estimates from the Last Glacial Maximum (LGM). Using the current habitat suitability data, a generalized linear model (GLM) was built to predict sex ratios based on habitat suitability. This model was then applied to the LGM habitat suitability data to predict historical sex ratios.</p>
<p>Two scatter plots were generated to visualize the relationship between sex ratios and habitat suitability. The scatter plot for current conditions (<code>Figure 4: Current Sex Ratios vs Habitat Suitability</code>) displays a slight negative correlation between habitat suitability and sex ratios, suggesting that in habitats with higher suitability, the proportion of females is marginally higher than that of males. The data points are scattered around the trendline, indicating some variability in the current conditions. The scatter plot for historical conditions (<code>Figure 5: Historical Sex Ratios vs Habitat Suitability</code>) shows a stronger negative correlation compared to the current conditions. This implies that during the LGM, more suitable habitats had a significantly higher proportion of females. Interestingly, all historical data points align closely with the trendline, suggesting a consistent pattern across the landscape during the LGM. This close alignment may indicate that the model could benefit from further refinement to capture more variability in historical data.</p>
<p>The stronger negative correlation in the historical plot indicates that climatic conditions during the LGM had a more pronounced impact on sex ratios. This could be due to harsher environmental pressures, which favored a higher proportion of females in suitable habitats. The differences between current and historical trends highlight how changing climate conditions have influenced sex ratio dynamics over time. While the current trend shows a mild impact, the historical trend underscores the significant role of past climate conditions in shaping these patterns. These findings provide insights into the evolutionary and ecological responses of <em>Araptus attenuatus</em> to climatic changes. The consistent pattern in the historical data suggests that sex ratio distribution has been a critical factor in the species’ adaptation to changing environments. The close alignment of historical data points with the trendline may indicate that the model could benefit from further refinement. Introducing additional variables or interactions could help capture more variability in historical data, providing a more nuanced understanding of sex ratio dynamics.</p>
<p>To further support this analysis, a detailed table (<code>Table 7: Sex Ratios Across Sites [Current vs Historical]</code>) compares sex ratios across various sites for both current and historical periods. The table reveals the sex ratios of <em>Araptus attenuatus</em> at multiple sites during both the current period and the LGM. For instance, Site 1 has a current sex ratio of 0.46 and a historical sex ratio of 0.6133472. Similarly, Site 10 has a current sex ratio of 0.6 and a historical sex ratio of 0.6377662, while Site 11 shows a current sex ratio of 0.56 compared to a historical sex ratio of 0.6346515. These examples indicate that, in many cases, the historical sex ratio was higher than the current one, suggesting an increase in the proportion of females during the LGM.</p>
<p>Figures 6 (<code>Figure 6: Historical Habitat Suitability for Araptus attenuatus</code>) and 7 (<code>Figure 7: Current Habitat Suitability for Araptus attenuatus</code>) further support this analysis spatially by illustrating the habitat suitability for <em>Araptus attenuatus</em> during both current and historical periods. These figures visually reinforce the patterns observed in the scatter plots and table, providing additional context for understanding how spatial variability in habitat suitability has influenced sex ratio distributions over time.</p>
<p>In summary, the application of the current conditions model to historical habitat suitability data revealed that climatic differences during the LGM had a stronger influence on sex ratios. This trend underscores the importance of climate in shaping the distribution and dynamics of <em>Araptus attenuatus</em> populations across the landscape. Additionally, the close alignment of historical data points with the trendline suggests potential areas for model improvement to capture more variability. The detailed table further supports the analysis by providing specific sex ratios for both current and historical periods across various sites.</p>
<hr>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>The primary goal of this study was to explore the extent to which changing climate may have influenced sex ratio divergence across different locations in the Sonora Desert bark beetle, <em>Araptus attenuatus</em>. As climate change continues to impact ecosystems worldwide, it is critical to assess how these shifts may affect population dynamics and the genetic structure of species, particularly those with limited mobility or specialized habitat requirements, such as <em>A. attenuatus</em>.</p>
<p>In examining the sex ratio data across 31 sampling sites within the Sonora Desert, it became apparent that climate-related factors could be playing a significant role in influencing sex ratio patterns. Several key findings emerged from this analysis, shedding light on potential connections between climatic shifts and observed sex ratio divergence.</p>
<section id="temperature-and-habitat-suitability" class="level4">
<h4 class="anchored" data-anchor-id="temperature-and-habitat-suitability">Temperature and Habitat Suitability</h4>
<p>One of the most striking results of the study is the relationship between temperature trends and the sex ratio divergence across the various sites. Warmer temperatures, associated with climate change, may be contributing to differential survival and reproductive success between male and female beetles. In many insect species, including beetles, temperature has been shown to affect the development and sex determination processes, leading to skewed sex ratios in certain environments. For example, in ectothermic species, such as <em>A. attenuatus</em>, temperature may influence the rate of development, growth, and survival of male and female individuals differently, potentially leading to higher mortality rates for one sex under specific climatic conditions.</p>
<p>Our analysis of habitat suitability, based on the current climate and the Last Glacial Maximum (LGM) conditions, further supported the idea that climate-induced changes in habitat availability may be influencing the distribution of <em>A. attenuatus</em> populations. Sites with more suitable current habitat conditions, indicated by higher suitability index values, were often associated with less pronounced sex ratio divergence. In contrast, areas with marginal habitat conditions, such as those affected by temperature extremes or drought, exhibited greater sex ratio imbalances. This suggests that as climate change alters habitat suitability, it could be indirectly influencing the balance of male and female populations.</p>
</section>
<section id="local-environmental-stressors-and-sex-ratio-divergence" class="level4">
<h4 class="anchored" data-anchor-id="local-environmental-stressors-and-sex-ratio-divergence">Local Environmental Stressors and Sex Ratio Divergence</h4>
<p>The divergence in sex ratios among sites may also be attributed to local environmental stressors exacerbated by climate change. Factors such as drought, changes in precipitation patterns, and the increased frequency of extreme weather events could further compound the effects of rising temperatures on beetle populations. Drought stress, for instance, can negatively impact the availability of resources for beetles, which in turn could influence their reproductive output and survival. Under such conditions, one sex may be more vulnerable than the other, potentially leading to skewed sex ratios.</p>
<p>Additionally, the potential for genetic or adaptive factors to play a role in sex ratio divergence should not be overlooked. Populations in more extreme environments may exhibit adaptations that influence their reproductive strategies, such as skewed sex ratios as a response to environmental pressures. Further investigation into the genetic basis of sex determination in <em>A. attenuatus</em> would be necessary to determine whether these patterns are driven by evolutionary or phenotypic plasticity mechanisms in response to climate change.</p>
</section>
<section id="implications-for-future-research" class="level4">
<h4 class="anchored" data-anchor-id="implications-for-future-research">Implications for Future Research</h4>
<p>While this study suggests a potential link between climate change and sex ratio divergence in <em>A. attenuatus</em>, it is important to note that several confounding factors may also contribute to the observed patterns. For example, differences in habitat quality, interspecific competition, and predation pressures could also influence sex ratios independently of climate factors. Additionally, the temporal scale of climate change effects on population dynamics may vary, and the observed sex ratio imbalances may reflect short-term fluctuations rather than long-term trends.</p>
<p>Further studies examining the long-term impacts of climate change on <em>A. attenuatus</em> populations across broader spatial scales and over extended periods would be valuable in confirming the role of climate in shaping sex ratio patterns. Incorporating other climate variables, such as shifts in humidity, precipitation, and the frequency of extreme weather events, would provide a more comprehensive understanding of how climate change is influencing sex ratio divergence in this species.</p>
<p>Moreover, integrating genetic analyses with demographic data could help reveal whether climate-induced changes in sex ratios are driven by adaptive responses or simply reflect ecological pressures. Understanding the genetic underpinnings of sex determination and the potential for climate-driven selection will be crucial for predicting how populations of <em>A. attenuatus</em> may respond to future climate scenarios.</p>
</section>
<section id="conclusion" class="level4">
<h4 class="anchored" data-anchor-id="conclusion">Conclusion</h4>
<p>In conclusion, the study highlights the potential for climate change to drive sex ratio divergence among <em>Araptus attenuatus</em> populations in the Sonora Desert. While the data suggest that temperature and habitat suitability are key factors influencing sex ratio patterns, the complex interplay of climate variables, local environmental stressors, and genetic factors warrants further investigation. By better understanding the mechanisms behind sex ratio divergence in response to climate change, we can develop more effective conservation strategies to mitigate the impacts of a warming climate on this species and other desert-adapted organisms.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>